# This file was generated by GoReleaser. DO NOT EDIT.
cask "concept2garmin" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "fc7e1f54f9bd908f811379ad15b2e4523f63a7940aa0f86922562d49e9a2ad71"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a45e049d11340f9e71403a885d4ae922c9cdc8defbcf89db21bc5a1511b22fc5"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c78dfa1b0ec7ba37fb33619efff66a30f42c5cb54460307b50d43cc659669025"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7f0f027e48966b040581369a80c954e9392bb920fe8988278a9298c9df59524"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "concept2garmin"
  desc "List and download Concept2 logbook workouts as Garmin-compatible TCX files"
  homepage "https://github.com/eoinaokane/concept2garmin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "concept2garmin"

  # No zap stanza required
end
