# This file was generated by GoReleaser. DO NOT EDIT.
cask "concept2upload" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "4f98597a40a291d721e6a5a516d4bc0bfcffc4b9d94ccfd2e9b4c5518ce84f9d"
      url "https://github.com/eoinaokane/concept2upload/releases/download/v#{version}/concept2upload_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aae8ff113d7e868415a8cf2d90b15d030959cb2594d0b558414911004e28061a"
      url "https://github.com/eoinaokane/concept2upload/releases/download/v#{version}/concept2upload_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e72c05cd92be4e2e26ec86dfbc058834413861064bad69149273d9241e5afcf"
      url "https://github.com/eoinaokane/concept2upload/releases/download/v#{version}/concept2upload_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "51666fc99c2cc5069b72e2c92d0695ce2f9325bb910bc39f5faeca792b438c2c"
      url "https://github.com/eoinaokane/concept2upload/releases/download/v#{version}/concept2upload_#{version}_linux_amd64.tar.gz"
    end
  end

  name "concept2upload"
  desc "Download Concept2 logbook workouts as Garmin-compatible TCX files and upload them to Strava"
  homepage "https://github.com/eoinaokane/concept2upload"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "concept2upload"

  # No zap stanza required
end
