# This file was generated by GoReleaser. DO NOT EDIT.
cask "concept2garmin" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "67a33d4efc66b24248bd0c52d64e812401c8ec7ead422414458e2521fc878eeb"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ade9c676b3876623d58090f353c7eb898b3789dc930b15a6dcbb7ae39872a4cd"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d155250cec3fc09b6d6550ac2ff843f40b657c4ee13a248b272a581875ba4723"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c5d1770a1634aef1cc0715ae60b77f1efdefa1cc81c91a0665c7ed9474ff2ea7"
      url "https://github.com/eoinaokane/concept2garmin/releases/download/v#{version}/concept2garmin_#{version}_linux_amd64.tar.gz"
    end
  end

  name "concept2garmin"
  desc "List and download Concept2 logbook workouts as Garmin-compatible TCX files"
  homepage "https://github.com/eoinaokane/concept2garmin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "concept2garmin"

  # No zap stanza required
end
